### ISSUE TITLE
Points per rum no longer matches the live game

### ISSUE THREAD

**Issue by Pheubel** [Biffo89/Trouble-Brewing#3]
As per 4 september, each bottle of rum deposited will now be worth 10 point, as seen in [this blog post](https://secure.runescape.com/m=news/araxxor-tweaks--poll-82-updates?oldschool=1).

This should be an easy change in the code. as it is essentially changing a 2 to a 10

**Comment by Biffo89** [comment]
Let me know if you'd like to be added as an author for this, as I don't really play anymore

**Comment by fuzxi** [comment]
@Biffo89 Could you please open a pull request against https://github.com/runelite/plugin-hub so that the plugin gets updated in the hub? The available version still shows the old values.
